sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: AcZNjzi4FimWLiEFikXyyiFr/B7P1QgAUgGaOp3lM8Kb07WcEAaRwjp3dg3nnq0++5vNJHnuzTaKxsON04Yyyq5fOR6jByITUZUo3vnl/x8Xpk29YChNyGQd6SKgvemgtKml18KI9zl+JT7Z6yABWqyYhP+SrfseJ0+ClepIRYLyM/NF6f/s1mX66V78CFMI08+dds5IeN5wz2YlYMZWPW6I8RAETUSFwOWH0XfKSSPrhhSIApekbrhVKzY1XZRUZ33NUBfEyMnEsIIcDRlhvLrmhxCr4oC8ahp8LLFju27JTnNC9z2IvzVvdpzixWSRmqX9cOeZNHjdWXbalN9hCIe985qJMiJBoBh8mz+Y7HNfKtoHXfk8X34bYF8gquFd/UPdxBdXOTA19ctrWeqpNVyVwh0LK7tY3OIc+MlxXjkHyfoS7Fva20rnW5LRixg5TLkizbE8tGsWgjct2OqRv2RyhbWDWyUXBrzDJAl72jE3M5sTQ8BombVEvn9h90nTfUVE0abAwY4i3uNiBQe86EgYXwNqta+hYKrCIDguJOtflMkwf7fa0gdOUUIG3LkCocNC/SPXpr9eNgcVp+yYQ3PzYHHUzmwDR+J6Cl6kmZRwBo3+0QnwvpPaDb2otEG5tU1xQJklQBCfjP/PICRxjB+1v5qjot6QsLd5Xn21hZA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Trespasser-Volume-3_6221
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy